config/routes.rb
Rails.application.routes.draw do
  resources :classification_funds

  root 'classification_funds#index'

end

app/models/classification_fund.rb
class ClassificationFund
  # < ActiveRecord::Base

  attr_accessor :code, :name, :net_value_today, :accumulative_value_today,
                :net_value_yesterday, :accumulative_value_yesterday,
                :increased_value, :increased_rate, :market_price, :rate, :fee,
                :surplus_rate

  def surplus_rate_str
    unless @surplus_rate.nil?
      @surplus_rate.round(3)
    end
  end

  def self.fetch_data
    # http://fund.eastmoney.com/Data/Fund_JJJZ_Data.aspx?&letter=&gsid=0&text=&sort=dwjz,desc&page=1,442&dt=1433596756999&atfc=
    uri = URI('http://fund.eastmoney.com/Data/Fund_JJJZ_Data.aspx?')

    params = {
        :t => 1,
        :lx => 9,
        :letter => '',
        :gsid => 0,
        :text => '',
        :sort => 'dwjz,desc',
        :page => '1,500',
        :dt => DateTime.now.strftime('%Q'),
        :atfc => ''
    }

    request = Net::HTTP::Get.new(uri.path + '?' + params.collect { |k, v| "#{k}=#{CGI::escape(v.to_s)}" }.join('&'))
    request['accept-encoding'] ='none'

    http = Net::HTTP.new(uri.host, 80)
    http.use_ssl = false

    response = http.request(request)
    data = response.body.to_s[/\[\[.+\]\]/]

    parsed_json = ActiveSupport::JSON.decode(data)    
    classification_fund_set_array = ClassificationFundSet.init_fund_set_array
    
    parsed_json.each do |r|
      classification_fund_set_array.each do |s|
        f = nil
        if s.parent_fund.code == r[0]
          f = s.parent_fund
        elsif s.fund_a.code == r[0]
          f = s.fund_a
        elsif s.fund_b.code == r[0]
          f = s.fund_b
        end

        unless f.nil?
          f.name = r[1]
          f.net_value_today = r[3]
          f.accumulative_value_today = r[4]
          f.net_value_yesterday = r[5]
          f.accumulative_value_yesterday = r[6]
          f.increased_value = r[7]
          f.increased_rate = r[8] # this value is %
          f.market_price = r[9]
          f.rate = r[10]
        end
      end
    end

    classification_fund_set_array.each do |s|
      s.calc_surplus_rate
    end

    classification_fund_set_array.sort_by! { |s| s.parent_fund.surplus_rate || 0}.reverse
  end

end

app/models/classification_fund_set.rb
class ClassificationFundSet
  attr_accessor :parent_fund, :fund_a, :fund_b

  def initialize
    @parent_fund = ClassificationFund.new
    @fund_a = ClassificationFund.new
    @fund_b = ClassificationFund.new
  end

  def to_a
    [@parent_fund, @fund_a, @fund_b]
  end

  def calc_surplus_rate
    unless @parent_fund.net_value_yesterday.blank?
      @parent_fund.surplus_rate = (@fund_a.market_price.to_f + @fund_b.market_price.to_f)/2/@parent_fund.net_value_today.to_f
    end
  end

  def self.init_fund_set_array
    fund_codes = ['167503','150275','150276','160516','150225','150226','161022','150152','150153','161026','150209','150210','161024','150181','150182','161027','150223','150224','161028','150211','150212','161025','150194','150195','161029','150241','150242','164818','150247','150248','160218','150117','150118','160222','150198','150199','160219','150130','150131','160221','150196','150197','161223','150213','150214','164705','150169','150170','164905','150217','150218','160136','150295','150296','160629','150203','150204','160628','150192','150193','160639','150277','150278','160630','150205','150206','160632','150229','150230','160640','150279','150280','160626','150179','150180','160638','150273','150274','160631','150227','150228','160625','150177','150178','160633','150235','150236','160620','150100','150101','164402','150221','150222','163116','150231','150232','163115','150186','150187','163113','150171','150172','163114','150184','150185','164304','150190','150191','165521','150157','150158','165519','150148','150149','165520','150150','150151','165522','150173','150174','161831','150175','150176','161721','150207','150208','161725','150269','150270','161724','150251','150252','161720','150200','150201','161723','150249','150250','168201','150265','150266']
    fund_fees = [5,10,12,12,12,12,12,12,12,0,10,0,10,0,0.5,12,12,6,12,12,12,12,12,12,12,12,12,12,12,12,12,5,10,12,10,10,12,12,12,10,12,10,10,10,10,10,0]

    fund_set_array = Array.new

    fund_codes.each_with_index do |f, i|
      if i % 3 == 0
        fund_set = ClassificationFundSet.new
        fund_set.parent_fund.code = f
        fund_set.parent_fund.fee = fund_fees[i / 3]
        fund_set.fund_a.code = fund_codes[i+1]
        fund_set.fund_b.code = fund_codes[i+2]
        fund_set_array.push(fund_set)
      end
    end

    fund_set_array
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classification_funds_controller.rb
class ClassificationFundsController < ApplicationController
  before_action :set_classification_fund, only: [:show, :edit, :update, :destroy]

  # GET /classification_funds
  # GET /classification_funds.json
  def index
    @classification_fund_sets = ClassificationFund.fetch_data
  end

  # GET /classification_funds/1
  # GET /classification_funds/1.json
  def show
  end

  # GET /classification_funds/new
  def new
    @classification_fund = ClassificationFund.new
  end

  # GET /classification_funds/1/edit
  def edit
  end

  # POST /classification_funds
  # POST /classification_funds.json
  def create
    @classification_fund = ClassificationFund.new(classification_fund_params)

    respond_to do |format|
      if @classification_fund.save
        format.html { redirect_to @classification_fund, notice: 'Classification fund was successfully created.' }
        format.json { render :show, status: :created, location: @classification_fund }
      else
        format.html { render :new }
        format.json { render json: @classification_fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classification_funds/1
  # PATCH/PUT /classification_funds/1.json
  def update
    respond_to do |format|
      if @classification_fund.update(classification_fund_params)
        format.html { redirect_to @classification_fund, notice: 'Classification fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @classification_fund }
      else
        format.html { render :edit }
        format.json { render json: @classification_fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classification_funds/1
  # DELETE /classification_funds/1.json
  def destroy
    @classification_fund.destroy
    respond_to do |format|
      format.html { redirect_to classification_funds_url, notice: 'Classification fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classification_fund
      @classification_fund = ClassificationFund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classification_fund_params
      params[:classification_fund]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classification_funds_helper.rb
module ClassificationFundsHelper
end

app/views/classification_funds/_form.html.slim
= form_for @classification_fund do |f|
  - if @classification_fund.errors.any?
    #error_explanation
      h2 = "#{pluralize(@classification_fund.errors.count, "error")} prohibited this classification_fund from being saved:"
      ul
        - @classification_fund.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/classification_funds/edit.html.slim
h1 Editing classification_fund

== render 'form'

= link_to 'Show', @classification_fund
'|
= link_to 'Back', classification_funds_path

app/views/classification_funds/index.html.slim
h1 天天基金 分级基金
section#all-funds
  .container
    table#classification-funds
      thead
        tr
          th 自定义序列
          th 基金代码
          th 基金简称
          th 今日单位净值
          th 今日累计净值
          th 昨日单位净值
          th 昨日累计净值
          th 日增长值
          th 日增长率
          th 市价
          th 折价率
          th 费率
          th 溢价率
      tfoot
        tr
          th 自定义序列
          th 基金代码
          th 基金简称
          th 今日单位净值
          th 今日累计净值
          th 昨日单位净值
          th 昨日累计净值
          th 日增长值
          th 日增长率
          th 市价
          th 折价率
          th 费率
          th 溢价率
      tbody
        - @classification_fund_sets.each_with_index do |s, i|
          - s.to_a.each_with_index do |classification_fund, j|
            tr
              td = (i + 1).to_s + '.' + j.to_s
              td = classification_fund.code
              td = classification_fund.name
              td = classification_fund.net_value_today
              td = classification_fund.accumulative_value_today
              td = classification_fund.net_value_yesterday
              td = classification_fund.accumulative_value_yesterday
              td = classification_fund.increased_value
              td = number_to_percentage(classification_fund.increased_rate, precision: 2)
              td = classification_fund.market_price
              td = number_to_percentage(classification_fund.rate, precision: 2)
              td = classification_fund.fee
              td = classification_fund.surplus_rate_str

app/views/classification_funds/new.html.slim
h1 New classification_fund

== render 'form'

= link_to 'Back', classification_funds_path

app/views/classification_funds/show.html.slim
p#notice = notice


= link_to 'Edit', edit_classification_fund_path(@classification_fund)
'|
= link_to 'Back', classification_funds_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Fund
    = stylesheet_link_tag    'application', media: 'all'
    link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
    link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css"
    /link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
    = javascript_include_tag 'application'
    script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"
    /script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"
    = csrf_meta_tags
  body
    = yield